name: Acquire activation file
on:
  push:
  schedule:
    - cron: '0 23 * * *'
    
jobs:
  activation:
    name: Request manual activation file on version ${{ matrix.unityVersion }} 🔑
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.20f1
          - 2020.3.0f1


    steps:

    # Request manual activation file
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2
      with:
        unityVersion: ${{ matrix.unityVersion }}

    # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
